src/apps/employees/urls.py
from django.urls import path
from .views import EmployeesList, EmployeeUpdate, EmployeeDelete, EmployeeCreate, pdf_reportlab, Pdf

urlpatterns = [
    path('', EmployeesList.as_view(), name='employees_list'),
    path('edit/<int:pk>', EmployeeUpdate.as_view(), name='employees_update'),
    path('delete/<int:pk>', EmployeeDelete.as_view(), name='employees_delete'),
    path('new/', EmployeeCreate.as_view(), name='employees_create'),
    path('pdf-reportlab/', pdf_reportlab, name='pdf_reportlab'),
    path('relatorio-html/', Pdf.as_view(), name='relatorio_html'),
]

src/gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from apps.base.views import UserViewSet, GroupViewSet
from apps.employees.api.views import EmployeeViewSet
from apps.register_hours.api.views import RegisterHourViewSet


# Rest Framework
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'api/employees', EmployeeViewSet)
router.register(r'api/hours-extras', RegisterHourViewSet)

urlpatterns = [
    path('', include('apps.base.urls')),
    path('employees/', include('apps.employees.urls')),
    path('departaments/', include('apps.departments.urls')),
    path('documents/', include('apps.documents.urls')),
    path('hours-extras/', include('apps.register_hours.urls')),
    path('company/', include('apps.companies.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    # Rest Framework
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/documents/models.py
from django.db import models
from django.urls import reverse

from ..employees.models import Employee

class Document(models.Model):
    description = models.CharField(max_length=120)
    belongs_to = models.ForeignKey(Employee, on_delete=models.PROTECT)
    file = models.FileField(upload_to='files')

    def __str__(self):
        return self.description

    def get_absolute_url(self):
        return reverse('employees_update', args=[self.belongs_to.id])

src/apps/employees/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from ..departments.models import Department
from ..companies.models import Company

class Employee(models.Model):
    name = models.CharField(max_length=120)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departments = models.ManyToManyField(Department)
    company = models.ForeignKey(Company, on_delete=models.PROTECT, null=True, blank=True)

    @property
    def total_hours(self):
        total = self.registerhour_set.all().aggregate(Sum('hours'))['hours__sum']
        return total

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('employees_list')

src/apps/register_hours/models.py
from django.db import models
from django.urls import reverse

from ..employees.models import Employee


class RegisterHour(models.Model):
    justification = models.CharField(max_length=120)
    employee = models.ForeignKey(Employee, on_delete=models.PROTECT)
    hours = models.DecimalField(max_digits=5, decimal_places=2)
    is_used = models.BooleanField(default=False)

    def __str__(self):
        return self.employee.name

    def get_absolute_url(self):
        return reverse('register_hours_update', args=[self.id])

src/apps/employees/api/views.py
from apps.employees.models import Employee
from rest_framework import viewsets
from apps.employees.api.serializers import EmployeeSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication

class EmployeeViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

src/apps/employees/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, View
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from .models import Employee

# Used for lib reportab
import io
from reportlab.pdfgen import canvas

# used for lib xhtml2pdf
from django.template.loader import get_template
import xhtml2pdf.pisa as pisa

class EmployeesList(ListView):
    model = Employee

    def get_queryset(self):
        company_current = self.request.user.employee.company
        return Employee.objects.filter(company=company_current)


class EmployeeUpdate(UpdateView):
    model = Employee
    fields = ['name', 'departments']


class EmployeeDelete(DeleteView):
    model = Employee
    success_url = reverse_lazy('employees_list')


class EmployeeCreate(CreateView):
    model = Employee
    fields = ['name', 'departments']

    def form_valid(self, form):
        obj = form.save(commit=False)
        username = obj.name.split(" ")
        obj.company = self.request.user.employee.company
        obj.user = User.objects.create(username=username[0])
        return super(EmployeeCreate, self).form_valid(form)


def pdf_reportlab(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="pdfteste.pdf"'

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)

    p.drawString(10, 810, "Hello, Word!")

    palavras = ['palavra1', 'palavra2', 'palavra2']

    y = 790
    for palavra in palavras:
        p.drawString(10, y, palavra)
        y -= 40

    p.showPage()
    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    return response


class Render:

    @staticmethod
    def render(path: str, params: dict, filename: str):
        template = get_template(path)
        html = template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(io.BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            response = HttpResponse(response.getvalue(), content_type='application/pdf')
            response['Content-Disposition'] = 'attachment; filename=%s.pdf' % filename
            return response
        else:
            return HttpResponse("Error Redering PDF", status=500)


class Pdf(View):

    def get(self, request):
        params = {
            'today': 'Variavel teste today',
            'sales': 'Variavel teste sales',
            'request': request,
        }
        return Render.render('employees/relatorio.html', params, 'testenovo')

src/apps/employees/templates/employees/employee_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Confirmar</button>
    </form>
{% endblock main %}

src/apps/employees/templates/employees/employee_form.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button type="submit">Salvar</button>
    </form>
    <br>
    {% if object %}
    <a href="{% url 'documents_create' object.id %}" class="btn btn-primary">Adicionar Documento</a>
    {% endif %}
    <div class="row">
    <div class="col-md-12">
        <h3>Documentos do Funcionário</h3>
    </div>
    {% for document in object.document_set.all %}
        <div class="col-md-3">
            <img src="{{ document.file.url }}" alt="">
            <p>{{ document.description }}</p>
        </div>
    {% endfor %}
    </div>
    <div class="row">
        <div class="col-md-12">
            <h3>Banco de Horas</h3>
        </div>
        {% for register in object.registerhour_set.all %}
        <div class="col-md-3">
            <p><strong>Justificativa:</strong> {{ register.justification }}</p>
            <p><strong>Horas Extras:</strong> {{ register.hours }}</p>
            <a href="{% url 'register_hours_update' register.id %}" class="btn btn-primary">Editar</a>
        </div>
        {% endfor %}
        <p><strong>Total de horas extras:</strong> {{ object.total_hours }}</p>
    </div>
{% endblock main %}

src/apps/employees/templates/employees/employee_list.html
{% extends 'base.html' %}

{% block main %}

    {% for employee in object_list %}
        <a href="{% url 'employees_update' employee.id %}">{{ employee }}</a>
        <a href="{% url 'employees_delete' employee.id %}">Deletar</a>
        <br>
    {% endfor %}

    <a href="{% url 'employees_create' %}" class="btn btn-primary">Novo Funcionário</a>
{% endblock main %}

src/apps/employees/templates/employees/relatorio.html
{% extends 'base.html' %}

{% block main %}
    <div style="background-color: #ccc;width: 400px;height: 400px;">
    <h1>Meu Relatório</h1>
    <h2>{{ sales }}</h2>
    </div>
{% endblock %}